#!/bin/bash


hexchat & HEXPID=$! >/dev/null 2>&1


echo $HEXPID
#
HEXWINID=$(xdotool search --onlyvisible --sync --pid ${HEXPID} | tail -1)
#
echo $HEXWINID

xdotool key --window $HEXWINID Return
HEXWINID=$(xdotool search --onlyvisible --sync --pid ${HEXPID} | tail -1)
xdotool windowactivate --sync ${HEXWINID} key --clearmodifiers --delay 100 alt+o

 echo $HEXWINID





#xdotool windowfocus -sync 39846006 key --delay 500 Alt_L  Alt_R+O
#xdotool key --window 39845990 --delay 2000 Alt & xdotool key --window 39845990 o







#timeout 3 killall -9 -q -w hexchat >/dev/null


# xdotool search --onlyvisible --sync --pid 13193
#xdotool key --window 39845891 Return


#Geometry: 372x138


exit 0
